# Generated by Django 6.0.6 on 2026-06-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('package_type', models.CharField(choices=[('cultural', 'Cultural & Historical'), ('adventure', 'Adventure & Nature'), ('extreme', 'Extreme Adventure')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('price', models.IntegerField(help_text='Price in ETB')),
                ('duration_days', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
